# Generated by Django 4.0 on 2021-12-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do_follow_user', to='trip.customuser'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followerd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_follow_user', to='trip.customuser'),
        ),
    ]
