# Generated by Django 4.0 on 2021-12-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_alter_follow_follower_id_alter_follow_followerd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followerd_id',
        ),
    ]
