# Generated by Django 4.0 on 2021-12-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_remove_follow_followerd_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='followerd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_follow_user', to='trip.customuser'),
        ),
    ]
