# Generated by Django 4.0 on 2021-12-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
