# Generated by Django 4.0 on 2021-12-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='model/sea.jpeg', null=True, upload_to='post/'),
        ),
    ]
