# Generated by Django 4.0 on 2021-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, choices=[('北海道', '北海道'), ('沖縄', '沖縄'), ('東北', '東北'), ('関東', '関東'), ('東海', '東海'), ('北陸', '北陸'), ('近畿', '近畿'), ('山陽・山陰', '山陽・山陰'), ('四国', '四国'), ('海外', '海外')], default=None, max_length=100, null=True),
        ),
    ]
