# Generated by Django 4.0 on 2021-12-27 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_post_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='trip.customuser')),
                ('user_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='trip.customuser')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, choices=[('hokkaido', '北海道'), ('okinawa', '沖縄'), ('東北', '東北'), ('関東', '関東'), ('東海', '東海'), ('北陸', '北陸'), ('近畿', '近畿'), ('山陽・山陰', '山陽・山陰'), ('四国', '四国'), ('海外', '海外')], default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.room'),
        ),
    ]
