# Generated by Django 4.0 on 2021-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_chat_room_alter_post_area_delete_message_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.CharField(default='masa', max_length=100),
            preserve_default=False,
        ),
    ]
